2023-09-08 09:15:43,543:DEBUG:certbot._internal.main:certbot version: 2.6.0
2023-09-08 09:15:43,543:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2023-09-08 09:15:43,543:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/var/www/html', '--email', 'youremail@domain.com', '--agree-tos', '--no-eff-email', '-d', 'wp.thanhtha.name.vn', '-d', 'www.wp.thanhtha.name.vn']
2023-09-08 09:15:43,544:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2023-09-08 09:15:43,563:DEBUG:certbot._internal.log:Root logging level set at 30
2023-09-08 09:15:43,565:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2023-09-08 09:15:43,568:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A seperate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7fe2838672b0>
Prep: True
2023-09-08 09:15:43,569:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7fe2838672b0> and installer None
2023-09-08 09:15:43,569:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2023-09-08 09:15:43,632:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/1298247286', new_authzr_uri=None, terms_of_service=None), 47e6e91e78d30cb00656cfa545c615ec, Meta(creation_dt=datetime.datetime(2023, 9, 8, 8, 13, 16, tzinfo=<UTC>), creation_host='ceb47789cad1', register_to_eff=None))>
2023-09-08 09:15:43,633:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2023-09-08 09:15:43,638:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2023-09-08 09:15:44,545:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 752
2023-09-08 09:15:44,546:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 08 Sep 2023 09:15:44 GMT
Content-Type: application/json
Content-Length: 752
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "QUQCtBx9Z9w": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-01/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2023-09-08 09:15:44,563:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): r3.o.lencr.org:80
2023-09-08 09:15:44,748:DEBUG:urllib3.connectionpool:http://r3.o.lencr.org:80 "POST / HTTP/1.1" 200 503
2023-09-08 09:15:44,753:DEBUG:certbot.ocsp:OCSP response for certificate /etc/letsencrypt/archive/wp.thanhtha.name.vn/cert1.pem is signed by the certificate's issuer.
2023-09-08 09:15:44,755:DEBUG:certbot.ocsp:OCSP certificate status for /etc/letsencrypt/archive/wp.thanhtha.name.vn/cert1.pem is: OCSPCertStatus.GOOD
2023-09-08 09:15:44,763:DEBUG:certbot._internal.display.obj:Notifying user: Certificate not yet due for renewal
2023-09-08 09:15:44,763:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1864, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1590, in certonly
    should_get_cert, lineage = _find_cert(config, domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 360, in _find_cert
    action, lineage = _find_lineage_for_domains_and_certname(config, domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 390, in _find_lineage_for_domains_and_certname
    return _find_lineage_for_domains(config, domains)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 335, in _find_lineage_for_domains
    return _handle_identical_cert_request(config, ident_names_cert)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 286, in _handle_identical_cert_request
    response = display_util.menu(question, choices,
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 80, in menu
    return obj.get_display().menu(message, choices, default=default, cli_flag=cli_flag,
  File "/opt/certbot/src/certbot/certbot/_internal/display/obj.py", line 125, in menu
    code, selection = self._get_valid_int_ans(len(choices))
  File "/opt/certbot/src/certbot/certbot/_internal/display/obj.py", line 390, in _get_valid_int_ans
    ans = util.input_with_timeout(input_msg)
  File "/opt/certbot/src/certbot/certbot/_internal/display/util.py", line 68, in input_with_timeout
    raise EOFError
EOFError
2023-09-08 09:15:44,767:ERROR:certbot._internal.log:An unexpected error occurred:
2023-09-08 09:15:44,767:ERROR:certbot._internal.log:EOFError
